project_id = "zusoprnxqohoeonaqwiv"

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-user-chat]
verify_jwt = false

[functions.telegram-prepare-share]
verify_jwt = false

[functions.telegram-auth-bootstrap]
verify_jwt = false

[functions.loyalty-action]
verify_jwt = false

[functions.event-checkin-production]
verify_jwt = false

[functions.review-submit-production]
verify_jwt = false

[functions.social-production]
verify_jwt = false

[functions.telegram-social-profile]
verify_jwt = false

[functions.telegram-send-message]
verify_jwt = true

[functions.telegram-setup-webhook]
verify_jwt = true
